-- =============================================================================
-- File: 02_create_database_inventory.sql
-- Purpose: Create the DATABASE_INVENTORY table used by the sample APEX app.
-- Run as: DB_INV_APP connected directly to KBPDB.
-- Example:
--   sqlplus db_inv_app@KBPDB
--   @sql/02_create_database_inventory.sql
--
-- Note:
--   This script is intended for an initial setup and will fail if the table
--   already exists.
-- =============================================================================

SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 220
SET PAGESIZE 100
SET SERVEROUTPUT ON
SET VERIFY OFF

PROMPT
PROMPT =========================================================================
PROMPT Connection Check
PROMPT =========================================================================

SELECT USER AS connected_user,
       SYS_CONTEXT('USERENV', 'CON_NAME') AS current_container
FROM dual;

PROMPT
PROMPT =========================================================================
PROMPT Creating DATABASE_INVENTORY
PROMPT =========================================================================

CREATE TABLE database_inventory (
    database_id       NUMBER
                      GENERATED BY DEFAULT AS IDENTITY
                      CONSTRAINT database_inventory_pk PRIMARY KEY,
    database_name     VARCHAR2(30) NOT NULL,
    environment       VARCHAR2(20) NOT NULL,
    database_version  VARCHAR2(30),
    host_name         VARCHAR2(100),
    ip_address        VARCHAR2(45),
    platform          VARCHAR2(50),
    status            VARCHAR2(20)
                      DEFAULT 'AVAILABLE'
                      NOT NULL,
    created_date      DATE
                      DEFAULT SYSDATE
                      NOT NULL,
    notes             VARCHAR2(500),
    CONSTRAINT database_inventory_env_ck
        CHECK (
            environment IN (
                'DEVELOPMENT',
                'TEST',
                'UAT',
                'PRODUCTION'
            )
        ),
    CONSTRAINT database_inventory_status_ck
        CHECK (
            status IN (
                'AVAILABLE',
                'UNAVAILABLE',
                'MAINTENANCE'
            )
        )
);

PROMPT
PROMPT =========================================================================
PROMPT Table Definition
PROMPT =========================================================================

DESC database_inventory;

PROMPT
PROMPT DATABASE_INVENTORY table creation completed.
